### PR TITLE
tftypes: Return errors instead of panics with Value missing type in Transform() and (Value).Diff()

### LINKED ISSUE #92: Panic when transforming an empty tftypes.Value
### terraform-plugin-go version

```
v0.3.1
```

### Relevant provider source code

Confidential and under NDA, unfortunately.

### Terraform Configuration Files

Confidential and under NDA, unfortunately.

### Expected Behavior

An error should be returned, or the tftypes.Value should be built out to have just the transformed data in it.

### Actual Behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x119e65e]
goroutine 25 [running]:
github.com/hashicorp/terraform-plugin-go/tftypes.transform(0xc000341848, 0x0, 0x0, 0x0, 0x0, 0xc0005bec98, 0x0, 0x1d91a28, 0xc000341830, 0x0, ...)
	/[snip]/github.com/hashicorp/terraform-plugin-go@v0.3.1/tftypes/walk.go:179 +0x37e
github.com/hashicorp/terraform-plugin-go/tftypes.Transform(...)
	/[snip]/github.com/hashicorp/terraform-plugin-go@v0.3.1/tftypes/walk.go:112
```

### PR DESCRIPTION
**Pull request by bflad**
Closes #92

Previously:

```
--- FAIL: TestTransform (0.00s)
    --- FAIL: TestTransform/testCase=empty:missingTypeError (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x11c0409]

goroutine 45 [running]:
testing.tRunner.func1.2({0x129d200, 0x14bb030})
	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1212 +0x218
panic({0x129d200, 0x14bb030})
	/usr/local/Cellar/go/1.17/libexec/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform-plugin-go/tftypes.transform(0x0, {{0x0, 0x0}, {0x0, 0x0}}, 0x0)
	/Users/bflad/src/github.com/hashicorp/terraform-plugin-go/tftypes/walk.go:179 +0x689
github.com/hashicorp/terraform-plugin-go/tftypes.Transform(...)
	/Users/bflad/src/github.com/hashicorp/terraform-plugin-go/tftypes/walk.go:112
github.com/hashicorp/terraform-plugin-go/tftypes.TestTransform.func51(0xc0001d89c0)
	/Users/bflad/src/github.com/hashicorp/terraform-plugin-go/tftypes/walk_test.go:1659 +0xcc
testing.tRunner(0xc0001d89c0, 0xc000010a00)
	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1306 +0x35a
FAIL	github.com/hashicorp/terraform-plugin-go/tftypes	1.821s
```

Added the missing type exits to `transform()` and added `(AttributePathError).Error()` to fix go-cmp testing with that type's unexported `err` field. This then discovered `(Value).Diff()` can exhibit a similar panic due to missing type information:

```
--- FAIL: TestTransform (0.00s)
    --- FAIL: TestTransform/testCase=empty:missingTypeError (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x11a400e]

goroutine 66 [running]:
testing.tRunner.func1.2({0x129ec80, 0x14bf030})
	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1212 +0x218
panic({0x129ec80, 0x14bf030})
	/usr/local/Cellar/go/1.17/libexec/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform-plugin-go/tftypes.Value.Diff({{0x0, 0x0}, {0x0, 0x0}}, {{0x0, 0x0}, {0x0, 0x0}})
	/Users/bflad/src/github.com/hashicorp/terraform-plugin-go/tftypes/diff.go:78 +0x8e
github.com/hashicorp/terraform-plugin-go/tftypes.TestTransform.func51(0xc000209380)
	/Users/bflad/src/github.com/hashicorp/terraform-plugin-go/tftypes/walk_test.go:1674 +0x1c5
testing.tRunner(0xc000209380, 0xc000103b60)
```

Covering `TestValueDiffDiff` panics before fix:

```
--- FAIL: TestValueDiffDiff (0.00s)
    --- FAIL: TestValueDiffDiff/val1Empty (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x11a400e]

goroutine 21 [running]:
testing.tRunner.func1.2({0x129ec80, 0x14bf030})
	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/Cellar/go/1.17/libexec/src/testing/testing.go:1212 +0x218
panic({0x129ec80, 0x14bf030})
	/usr/local/Cellar/go/1.17/libexec/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform-plugin-go/tftypes.Value.Diff({{0x0, 0x0}, {0x0, 0x0}}, {{0x135dea0, 0xc0000a2630}, {0x128e7c0, 0xc00009e840}})
	/Users/bflad/src/github.com/hashicorp/terraform-plugin-go/tftypes/diff.go:78 +0x8e
github.com/hashicorp/terraform-plugin-go/tftypes.TestValueDiffDiff.func1(0xc000083ba0)
	/Users/bflad/src/github.com/hashicorp/terraform-plugin-go/tftypes/diff_test.go:554 +0x6b
testing.tRunner(0xc000083ba0, 0xc0000dc9a0)
```

### CODE REVIEW

File: tftypes/attribute_path_error.go [hunk 1]
```diff
@@ -11,6 +11,14 @@ type AttributePathError struct {
 	err  error
 }
 
+func (a AttributePathError) Equal(o AttributePathError) bool {
+	if !a.Path.Equal(o.Path) {
+		return false
+	}
+
```
Comment (paddycarver) [inline tftypes/attribute_path_error.go:18]: nitpick: can we add detection of an `Equal` method on the `err` here, and call that instead of comparing `err.Error()` if it exists?

**Review by paddycarver — APPROVED** [review]

File: tftypes/attribute_path_error.go (hunk 1 above)
Comment (bflad) [reply tftypes/attribute_path_error.go:18]: Are you referring to using `(reflect.Type).MethodName("Equal")` or is there a standard library type to assert against?

The last check here should probably be `errors.Is()` instead of `==` anyways.

Comment (bflad) [reply tftypes/attribute_path_error.go:18]: In the meantime have added unit testing for this new method with various scenarios including `nil` errors.

Comment (paddycarver) [reply tftypes/attribute_path_error.go:18]: I had in mind something like this: https://github.com/google/go-cmp/blob/395a0ac549058d781199661ca2e37cc636db43e4/cmp/compare.go#L309-L319

Forgetting that it would need to be reflection-based. Forget it, probably not worth it. :)

**Review by paddycarver — APPROVED** [review]
Still looks good to me.
